git:
  depth: false
  submodules: false
branches:
  only:
    - devel
    - wip
    - uat
    - master
language: ruby
cache: bundler
env:
  global:
    - CC_TEST_REPORTER_ID=0f406be899c2acbb5cdcd7b1ed8bbba40910c3c624673c6b723efc512d3bec09
services:
  - postgresql
before_script:
  - psql -c 'create database aker_auth_app_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
